(require 'package)

(defun pmh/first-time-setup ()
  "Use this when setting up on a new computer. Only really needs to be run once."
  (interactive)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (if (< emacs-major-version 27)
	  (package-initialize))
  (pmh/install-config-packages)
  (load "init.el"))

(defun pmh/install-config-packages ()
  (interactive)
  (progn
	(package-refresh-contents)
    (package-install 'org-jira)
    (package-install 'markdown-mode)
    (package-install 'treemacs)
        (package-install 'cloc)
    (package-install 'groovy-mode)
    (package-install 'obsidian)
    (package-install 'pandoc)
    (package-install 'nerd-icons)
	(nerd-icons-install-fonts)
    (package-install 'ox-pandoc)
    (package-install 'company-irony)
        (package-install 'rebecca-theme)
                (package-install 'all-the-icons)
	(package-install 'treemacs-nerd-icons)
	(package-install 'easysession)
		(pmh/compile-org-scratch)
	(package-install 'lsp-mode)
	(message "Installation Complete")))

(defun pmh/compile-org-scratch ()
  (interactive)
  (byte-compile-file "./org-scratch.el"))
